fix: workflow

diff --git a/Build_artefacts_arm64v8 b/Build_artefacts_arm64v8
--- a/Build_artefacts_arm64v8
+++ b/Build_artefacts_arm64v8
@@ -16,4 +16,5 @@ ENV USE_SYSTEM_FPM true
 RUN npm i --no-package-lock
 RUN df -h
 RUN npm run pack
+RUN scripts/appimage.sh || echo 'Create AppImage fails'
 RUN echo $(node -e "const package = require('./package.json'); console.log(package.version);") > ./build/installers/version
